services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ascend-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - ascend-network
    depends_on:
      - postgres

  auth:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=postgres
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3001
      - GOOGLE_CLIENT_ID_WEB=${GOOGLE_CLIENT_ID_WEB}
      - GOOGLE_CLIENT_ID_IOS=${GOOGLE_CLIENT_ID_IOS}
      - GOOGLE_CLIENT_ID_ANDROID=${GOOGLE_CLIENT_ID_ANDROID}
    depends_on:
      - postgres
    networks:
      - ascend-network

volumes:
  postgres_data:
  pgadmin_data:
  
networks:
  ascend-network:
    driver: bridge
