import 'package:ascend_app/features/networks/model/user_model.dart';

UserModel getUser(String id) {
  return generateUsers().firstWhere((element) => element.id == id);
}

List<UserModel> generateUsers() {
  return [
    UserModel(
      id: '1',
      name: 'John Doe',
      company: 'Company A',
      industry: 'Industry A',
      profilePic: 'assets/logo.jpg',
      coverpic: 'assets/pexels-karymefranca-1535907.jpg',
      bio: 'Engineer at Company A',
    ),
    UserModel(
      id: '2',
      name: 'Jane Doe',
      company: 'Company B',
      industry: 'Industry B',
      profilePic: 'assets/logo.jpg',
      coverpic: 'assets/pexels-karymefranca-1535907.jpg',
      bio: 'Manager at Company B',
    ),
    UserModel(
      id: '3',
      name: 'Alice',
      company: 'Company C',
      industry: 'Industry C',
      profilePic: 'assets/logo.jpg',
      coverpic: 'assets/pic 2.jpg',
      bio: 'Developer at Company C',
    ),
    UserModel(
      id: '4',
      name: 'Bob',
      company: 'Company D',
      industry: 'Industry D',
      profilePic: 'assets/logo.jpg',
      coverpic: 'assets/pic 2.jpg',
      bio: 'Designer at Company D',
    ),
    UserModel(
      id: '5',
      name: 'Charlie',
      company: 'Company E',
      industry: 'Industry E',
      profilePic: 'assets/logo.jpg',
      coverpic: 'assets/pic 3.jpg',
      bio: 'Analyst at Company E',
    ),
    UserModel(
      id: '6',
      name: 'David',
      company: 'Company F',
      industry: 'Industry F',
      profilePic: 'assets/logo.jpg',
      coverpic: 'assets/pic 3.jpg',
      bio: 'Consultant at Company F',
    ),
    UserModel(
      id: '7',
      name: 'Eve',
      company: 'Company G',
      industry: 'Industry G',
      profilePic: 'assets/pexels-karymefranca-1535907.jpg',
      coverpic: 'assets/image 4.jpg',
      bio:
          'HR at Company G lorem ipsum dolor sit amet consectetur adipiscing elit',
    ),
    UserModel(
      id: '8',
      name: 'Frank',
      company: 'Company H',
      industry: 'Industry H',
      profilePic: 'assets/pexels-karymefranca-1535907.jpg',
      coverpic: 'assets/image 4.jpg',
      bio:
          'Marketing at Company H lorem ipsum dolor sit amet consectetur adipiscing elit',
    ),
    UserModel(
      id: '9',
      name: 'Grace',
      company: 'Company I',
      industry: 'Industry I',
      profilePic: 'assets/pexels-karymefranca-1535907.jpg',
      coverpic: 'assets/image 4.jpg',
      bio:
          'Sales at Company I lorem ipsum dolor sit amet consectetur adipiscing elit',
    ),
    UserModel(
      id: '10',
      name: 'Henry',
      company: 'Company J',
      industry: 'Industry J',
      profilePic: 'assets/facebook.png',
      coverpic: 'assets/logo.jpg',
      bio:
          'Engineer at Company J lorem ipsum dolor sit amet consectetur adipiscing elit',
    ),
    UserModel(
      id: '11',
      name: 'Ivy',
      company: 'Company K',
      industry: 'Industry K',
      profilePic: 'assets/facebook.png',
      coverpic: 'assets/logo.jpg',
      bio:
          'Manager at Company K lorem ipsum dolor sit amet consectetur adipiscing elit',
    ),
    UserModel(
      id: '12',
      name: 'Jack',
      company: 'Company L',
      industry: 'Industry L',
      profilePic: 'assets/facebook.png',
      coverpic: 'assets/pic 2.jpg',
      bio: 'Developer at Company L',
    ),
    UserModel(
      id: '13',
      name: 'Kate',
      company: 'Company M',
      industry: 'Industry M',
      profilePic: 'assets/facebook.png',
      coverpic: 'assets/pic 2.jpg',
      bio: 'Designer at Company M',
    ),
    UserModel(
      id: '14',
      name: 'Liam',
      company: 'Company N',
      industry: 'Industry N',
      profilePic: 'assets/facebook.png',
      coverpic: 'assets/pic 3.jpg',
      bio: 'Analyst at Company N',
    ),
    UserModel(
      id: '15',
      name: 'Mia',
      company: 'Company O',
      industry: 'Industry O',
      profilePic: 'assets/facebook.png',
      coverpic: 'assets/pic 3.jpg',
      bio: 'Consultant at Company O',
    ),
    UserModel(
      id: '16',
      name: 'Nathan',
      company: 'Company P',
      industry: 'Industry P',
      profilePic: 'assets/facebook.png',
      coverpic: 'assets/image 4.jpg',
      bio: 'HR at Company P',
    ),
    UserModel(
      id: '17',
      name: 'Olivia',
      company: 'Company Q',
      industry: 'Industry Q',
      profilePic: 'assets/facebook.png',
      coverpic: 'assets/image 4.jpg',
      bio: 'Marketing at Company Q',
    ),
    UserModel(
      id: '18',
      name: 'Peter',
      company: 'Company R',
      industry: 'Industry R',
      profilePic: 'assets/facebook.png',
      coverpic: 'assets/image 4.jpg',
      bio: 'Sales at Company R',
    ),
    UserModel(
      id: '19',
      name: 'Quinn',
      company: 'Company S',
      industry: 'Industry S',
      profilePic: 'assets/facebook.png',
      coverpic: 'assets/logo.jpg',
      bio: 'Engineer at Company S',
    ),
    UserModel(
      id: '20',
      name: 'Rose',
      company: 'Company T',
      industry: 'Industry T',
      profilePic: 'assets/facebook.png',
      coverpic: 'assets/logo.jpg',
      bio: 'Manager at Company T',
    ),
  ];
}
