// Mocks generated by Mockito 5.4.5 from annotations
// in ascend_app/test/features/Messaging/data/datasources/remote_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i6;

import 'package:ascend_app/features/StartPages/repository/api_client.dart'
    as _i5;
import 'package:ascend_app/services/web_socket_service.dart' as _i3;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WebSocketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocketService extends _i1.Mock implements _i3.WebSocketService {
  MockWebSocketService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  bool get isRegistered => (super.noSuchMethod(
        Invocation.getter(#isRegistered),
        returnValue: false,
      ) as bool);

  @override
  _i4.Stream<Map<String, dynamic>> get messageStream => (super.noSuchMethod(
        Invocation.getter(#messageStream),
        returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
      ) as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Stream<_i3.ConnectionState> get connectionStatusStream =>
      (super.noSuchMethod(
        Invocation.getter(#connectionStatusStream),
        returnValue: _i4.Stream<_i3.ConnectionState>.empty(),
      ) as _i4.Stream<_i3.ConnectionState>);

  @override
  _i4.Stream<Map<String, String>> get typingStatusStream => (super.noSuchMethod(
        Invocation.getter(#typingStatusStream),
        returnValue: _i4.Stream<Map<String, String>>.empty(),
      ) as _i4.Stream<Map<String, String>>);

  @override
  _i4.Stream<Map<String, bool>> get readReceiptStream => (super.noSuchMethod(
        Invocation.getter(#readReceiptStream),
        returnValue: _i4.Stream<Map<String, bool>>.empty(),
      ) as _i4.Stream<Map<String, bool>>);

  @override
  _i4.Future<void> checkServerTlsInfo(
    String? host,
    int? port,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkServerTlsInfo,
          [
            host,
            port,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void debugSocketConnection() => super.noSuchMethod(
        Invocation.method(
          #debugSocketConnection,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<bool> connect(
    String? url,
    String? authToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [
            url,
            authToken,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  void sendMessage(Map<String, dynamic>? data) => super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [data],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> sendTypingNotification(String? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendTypingNotification,
          [conversationId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> markMessageAsRead(String? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMessageAsRead,
          [conversationId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool hasTypingActivity(String? conversationId) => (super.noSuchMethod(
        Invocation.method(
          #hasTypingActivity,
          [conversationId],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isAnyoneTyping(String? conversationId) => (super.noSuchMethod(
        Invocation.method(
          #isAnyoneTyping,
          [conversationId],
        ),
        returnValue: false,
      ) as bool);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i5.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Response> get(String? endpoint) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [endpoint],
        ),
        returnValue: _i4.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #get,
            [endpoint],
          ),
        )),
      ) as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> post(
    String? endpoint, {
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [endpoint],
          {#data: data},
        ),
        returnValue: _i4.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #post,
            [endpoint],
            {#data: data},
          ),
        )),
      ) as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> signUp({
    required String? firstName,
    required String? lastName,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [],
          {
            #firstName: firstName,
            #lastName: lastName,
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #signUp,
            [],
            {
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> forgotPassword(String? emailOrPhone) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [emailOrPhone],
        ),
        returnValue: _i4.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #forgotPassword,
            [emailOrPhone],
          ),
        )),
      ) as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> verifyCode({
    required String? emailOrPhone,
    required String? verificationCode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyCode,
          [],
          {
            #emailOrPhone: emailOrPhone,
            #verificationCode: verificationCode,
          },
        ),
        returnValue: _i4.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #verifyCode,
            [],
            {
              #emailOrPhone: emailOrPhone,
              #verificationCode: verificationCode,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> put(
    String? endpoint, {
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [endpoint],
          {#data: data},
        ),
        returnValue: _i4.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #put,
            [endpoint],
            {#data: data},
          ),
        )),
      ) as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> delete(String? endpoint) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [endpoint],
        ),
        returnValue: _i4.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #delete,
            [endpoint],
          ),
        )),
      ) as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> patch(
    String? endpoint, {
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [endpoint],
          {#data: data},
        ),
        returnValue: _i4.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #patch,
            [endpoint],
            {#data: data},
          ),
        )),
      ) as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> uploadFile(
    String? endpoint,
    _i6.File? file,
    String? context, {
    Map<String, String>? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [
            endpoint,
            file,
            context,
          ],
          {#body: body},
        ),
        returnValue: _i4.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #uploadFile,
            [
              endpoint,
              file,
              context,
            ],
            {#body: body},
          ),
        )),
      ) as _i4.Future<_i2.Response>);
}
