[package]
name = "api-client"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.40", features = ["serde"] }
flutter_rust_bridge = "2.9.0"
js-sys = "0.3.77"
openssl = { version = "0.10.71", features = ["vendored"] }
reqwest = { version = "0.12.15", features = ["json", "multipart"] }
serde = { version = "1.0.219", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
serde_json = "1.0.140"
thiserror = "2.0.12"
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
web-sys = { version = "0.3.77", features = ["console"] }

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]
