// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Notification {
  final int id;
  final int userId;
  final NotificationType type;
  final String message;
  final Value? payload;
  final bool? isRead;
  final DateTime? createdAt;
  final DateTime? updatedAt;

  const Notification({
    required this.id,
    required this.userId,
    required this.type,
    required this.message,
    this.payload,
    this.isRead,
    this.createdAt,
    this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      userId.hashCode ^
      type.hashCode ^
      message.hashCode ^
      payload.hashCode ^
      isRead.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Notification &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          userId == other.userId &&
          type == other.type &&
          message == other.message &&
          payload == other.payload &&
          isRead == other.isRead &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

enum NotificationType { welcome }
