[build]
# WASM
# target = "wasm32-unknown-unknown"
# iOS
# target = "aarch64-apple-ios"
# Android: aarch64-linux-android, armv7-linux-androideabi, i686-linux-android
#target = "aarch64-linux-android"

[target.aarch64-linux-android]
linker = "aarch64-linux-android21-clang"

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi21-clang"

[target.i686-linux-android]
linker = "i686-linux-android21-clang"

[target.aarch64-apple-ios]
linker = "aarch64-apple-ios-clang"