name: ascend_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter_svg: ^2.0.10
  flutter:
    sdk: flutter
  dio: ^5.4.0
  flutter_bloc: ^9.0.0
  readmore: ^3.0.0
  flex_color_scheme: ^8.0.0
  carousel_slider: ^5.0.0
  photo_view: ^0.15.0
  uuid: ^4.5.1
  flutter_secure_storage: ^8.0.0
  hive: ^2.2.3
  path_provider: ^2.0.14
  logger: ^1.4.0
  http: ^1.3.0

  url_launcher: ^6.1.14  # Use the latest version available
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.0.0
  dartz: ^0.10.1
  internet_connection_checker: ^3.0.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  hive_flutter: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg
    - assets/images_posts/
    - assets/
    - assets/logo/
    - assets/company_placeholder.png
