name: ascend_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:

  sdk: '>=3.7.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0  
  flutter_bloc: ^9.0.0
  readmore: ^3.0.0
  flex_color_scheme: ^8.0.0
  carousel_slider: ^5.0.0
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  


flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg
    - assets/images_posts/


    - assets/
    - assets/logo/
