/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmapiclient_free: (a: number, b: number) => void;
export const wasmapiclient_new: (a: number, b: number) => number;
export const wasmapiclient_set_auth_token: (a: number, b: number, c: number) => void;
export const wasmapiclient_get_auth_token: (a: number) => [number, number, number, number];
export const wasmapiclient_get_gateway_health: (a: number) => any;
export const wasmapiclient_login: (a: number, b: number, c: number, d: number, e: number) => any;
export const wasmapiclient_register: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => any;
export const wasmapiclient_resend_confirm_email: (a: number, b: number, c: number) => any;
export const wasmapiclient_update_password: (a: number, b: number, c: number, d: number, e: number) => any;
export const wasmapiclient_update_email: (a: number, b: number, c: number) => any;
export const wasmapiclient_forget_password: (a: number, b: number, c: number) => any;
export const wasmapiclient_reset_password: (a: number, b: number, c: number, d: number, e: number) => any;
export const wasmapiclient_delete_account: (a: number) => any;
export const wasmapiclient_logout: (a: number) => any;
export const wasmapiclient_get_local_user_profile: (a: number) => any;
export const wasmapiclient_update_local_user_profile: (a: number, b: any) => any;
export const wasmapiclient_upload_profile_picture: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => any;
export const wasmapiclient_delete_profile_picture: (a: number) => any;
export const wasmapiclient_upload_cover_photo: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => any;
export const wasmapiclient_delete_cover_photo: (a: number) => any;
export const wasmapiclient_upload_resume: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => any;
export const wasmapiclient_delete_resume: (a: number) => any;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_4: WebAssembly.Table;
export const __wbindgen_export_5: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h44b2e8785f7525ab: (a: number, b: number) => void;
export const closure243_externref_shim: (a: number, b: number, c: any) => void;
export const closure293_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
