name: dummy_cross
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  ed25519_edwards: ^0.3.1
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.9.0
  http: ^1.3.0
  logger: ^2.5.0
  logging: ^1.3.0
  rust_lib_dummy_cross:
    path: rust_builder
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
