// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class LoginResponse {
  final String token;
  final int userId;

  const LoginResponse({required this.token, required this.userId});

  @override
  int get hashCode => token.hashCode ^ userId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoginResponse &&
          runtimeType == other.runtimeType &&
          token == other.token &&
          userId == other.userId;
}

class RegisterResponse {
  final int userId;
  final String email;

  const RegisterResponse({required this.userId, required this.email});

  @override
  int get hashCode => userId.hashCode ^ email.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RegisterResponse &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          email == other.email;
}
