// Mocks generated by Mockito 5.4.5 from annotations
// in ascend_app/test/features/Messaging/presentation/bloc/messaging_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i7;

import 'package:ascend_app/features/Messaging/data/datasources/remote_datasource.dart'
    as _i2;
import 'package:ascend_app/features/Messaging/data/model/conversation_model.dart'
    as _i5;
import 'package:ascend_app/features/Messaging/data/model/message_model.dart'
    as _i6;
import 'package:ascend_app/services/web_socket_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MessagingRepoistoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessagingRepoistoryImpl extends _i1.Mock
    implements _i2.MessagingRepoistoryImpl {
  MockMessagingRepoistoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<Map<String, dynamic>> get messageStream => (super.noSuchMethod(
        Invocation.getter(#messageStream),
        returnValue: _i3.Stream<Map<String, dynamic>>.empty(),
      ) as _i3.Stream<Map<String, dynamic>>);

  @override
  _i3.Stream<_i4.ConnectionState> get connectionStatusStream =>
      (super.noSuchMethod(
        Invocation.getter(#connectionStatusStream),
        returnValue: _i3.Stream<_i4.ConnectionState>.empty(),
      ) as _i3.Stream<_i4.ConnectionState>);

  @override
  _i3.Stream<Map<String, String>> get typingStatusStream => (super.noSuchMethod(
        Invocation.getter(#typingStatusStream),
        returnValue: _i3.Stream<Map<String, String>>.empty(),
      ) as _i3.Stream<Map<String, String>>);

  @override
  _i3.Stream<Map<String, bool>> get readReceiptStream => (super.noSuchMethod(
        Invocation.getter(#readReceiptStream),
        returnValue: _i3.Stream<Map<String, bool>>.empty(),
      ) as _i3.Stream<Map<String, bool>>);

  @override
  _i3.Future<List<_i5.ConversationModel>> getConversations({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConversations,
          [],
          {#page: page},
        ),
        returnValue: _i3.Future<List<_i5.ConversationModel>>.value(
            <_i5.ConversationModel>[]),
      ) as _i3.Future<List<_i5.ConversationModel>>);

  @override
  _i3.Future<int> getUnseenCount() => (super.noSuchMethod(
        Invocation.method(
          #getUnseenCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i6.MessageModel>> getMessages(
    String? conversationId, {
    int? page = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessages,
          [conversationId],
          {#page: page},
        ),
        returnValue:
            _i3.Future<List<_i6.MessageModel>>.value(<_i6.MessageModel>[]),
      ) as _i3.Future<List<_i6.MessageModel>>);

  @override
  _i3.Future<String> sendMessage(
    String? receiverId,
    String? content, {
    String? contentType = 'text',
    _i7.File? file,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [
            receiverId,
            content,
          ],
          {
            #contentType: contentType,
            #file: file,
          },
        ),
        returnValue: _i3.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #sendMessage,
            [
              receiverId,
              content,
            ],
            {
              #contentType: contentType,
              #file: file,
            },
          ),
        )),
      ) as _i3.Future<String>);

  @override
  bool isConnected() => (super.noSuchMethod(
        Invocation.method(
          #isConnected,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isRegistered() => (super.noSuchMethod(
        Invocation.method(
          #isRegistered,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<bool> connectWebSocket() => (super.noSuchMethod(
        Invocation.method(
          #connectWebSocket,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> disconnectWebSocket() => (super.noSuchMethod(
        Invocation.method(
          #disconnectWebSocket,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void sendTypingNotification(String? conversationId) => super.noSuchMethod(
        Invocation.method(
          #sendTypingNotification,
          [conversationId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> markMessageAsSeen(String? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMessageAsSeen,
          [conversationId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  bool isAnyoneTyping(String? conversationId) => (super.noSuchMethod(
        Invocation.method(
          #isAnyoneTyping,
          [conversationId],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<bool> sendFileMessage({
    required String? conversationId,
    required String? receiverId,
    required _i7.File? file,
    required String? content,
    required String? fileType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendFileMessage,
          [],
          {
            #conversationId: conversationId,
            #receiverId: receiverId,
            #file: file,
            #content: content,
            #fileType: fileType,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
