name: Backend CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - backend-master
  pull_request:
    branches:
      - backend-master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get deploy script
        run: |
          curl -o deploy.sh \
          https://raw.githubusercontent.com/MRKDaGods/ascend/backend-master/scripts/deploy.sh

      - name: Deploy to VM
        env:
          PEM_KEY: ${{ secrets.PEM_KEY }}
          VM_USER: ${{ secrets.VM_USER }}
          VM_HOST: ${{ secrets.VM_HOST }}
        run: |
          echo Begin deployment

          echo Saving SSH key
          # Save SSH key
          echo "$PEM_KEY" > key.pem
          chmod 600 key.pem

          echo "Adding host to known_hosts"
          ssh-keyscan -H $VM_HOST >> ~/.ssh/known_hosts

          echo Copying deploy script
          # Copy the deploy.sh file to the VM
          scp -i key.pem -o StrictHostKeyChecking=no deploy.sh $VM_USER@$VM_HOST:~/deploy.sh

          echo SSH-ing into VM
          # SSH into the VM, add execute permissions, and run the script
          ssh -i key.pem -o StrictHostKeyChecking=no $VM_USER@$VM_HOST << 'EOF'
          cd ~
          chmod +x deploy.sh
          sudo ./deploy.sh
          EOF
